[tox]
minversion = 1.8
basepython = python3.6
envlist = py36-molecule-light
skipsdist = true

[testenv]
passenv = *
deps =
    -r tox-requirements.txt
    ansible210: ansible<3.0
    ansible30: ansible<3.1
commands =
    molecule test -s light --destroy always